quality gate

diff --git a/.github/workflows/sonarqube-analysis.yml b/.github/workflows/sonarqube-analysis.yml
--- a/.github/workflows/sonarqube-analysis.yml
+++ b/.github/workflows/sonarqube-analysis.yml
@@ -46,5 +46,21 @@ jobs:
           SONAR_HOST_URL: 'http://localhost:9000' # Adjust to your SonarQube local URL if necessary
         run: |
           mvn clean verify sonar:sonar -D'sonar.projectKey=bank-showcase' -D'sonar.login'=$SONAR_TOKEN -D'sonar.host.url=http://localhost:9000'
-            
+
+      - name: Check SonarQube Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: 'http://localhost:9000'
+        run: |
+          # Wait for the analysis to complete
+          sleep 30
+          # Query the SonarQube API to get the quality gate status
+          quality_gate_status=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=bank-showcase" | jq -r .projectStatus.status)
+
+          echo "Quality Gate Status: $quality_gate_status"
+          
+          if [[ "$quality_gate_status" != "OK" ]]; then
+              echo "Quality Gate failed"
+              exit 1  # Fail the job if the quality gate is not OK
+          fi
 
